### ISSUE TITLE
Reset pokemon after first sim

### ISSUE THREAD

**Issue by How45** [How45/Sim_Battle#1]
## You need to reset : Issue
Reset the poke stats after one has fallen

## Task
- [x] Reset any stats to normal state
- [x] Reset hp to normal state
- [x] Remove any debuffs
- [ ] Remove any items (This isn't an issue at current stage, just a placeholder)

**Comment by How45** [comment]
Watch out when you do add items into the sim
