### ISSUE TITLE
Spt Defence Vs Defence

### ISSUE THREAD

**Issue by How45** [How45/Sim_Battle#2]
https://github.com/How45/Sim_Battle/blob/caa6c2cf3ac51b6d8641d7396d03828c7a9dcfef/sim-battle/src/main/java/com/pokemon/App.java#L50-L51

## Issue : differentiate between 
Spt Defence and Defence or Spt Attack and Attack. This is for function getDamageMove

## Task
- [ ] Find what type of attack i.e. Speical use Spt
- [ ] Either edit function and add new one that changes between either Spt and normal
- [ ] Intergrate that back in for damage calculations
